### ISSUE TITLE
initial basemap toggle switch should be on

### ISSUE THREAD

**Issue by rgdonohue** [Danidue1/Halfmoon_Interactive#2]
Currently, the map loads and we're looking at the Google maps streets view, but the toggle switch in the Basemap Selection should indicate this.

![image](https://user-images.githubusercontent.com/1952205/27348214-7f2c1af0-55b0-11e7-9caf-7b872fa40ff9.png)

**Comment by Danidue1** [comment]
I was able to update that issue with the following code, that I'll sync up tonight:
$('#streetSwitch').prop('checked', true).change();

$('#streetSwitch').change(function(){
	if ($(this).is(':checked')) {
		$('#satSwitch').bootstrapToggle('off') &
		$('#nysSwitch').bootstrapToggle('off') &
		$('#hybridSwitch').bootstrapToggle('off')
	}
});
$('#satSwitch').change(function(){
	if ($(this).is(':checked')) {
		$('#streetSwitch').bootstrapToggle('off') &
		$('#nysSwitch').bootstrapToggle('off') &
		$('#hybridSwitch').bootstrapToggle('off')
	}
});
$('#nysSwitch').change(function(){
	if ($(this).is(':checked')) {
		$('#satSwitch').bootstrapToggle('off') &
		$('#streetSwitch').bootstrapToggle('off') &
		$('#hybridSwitch').bootstrapToggle('off')
	}
});
$('#hybridSwitch').change(function(){
	if ($(this).is(':checked')) {
		$('#streetSwitch').bootstrapToggle('off') &
		$('#nysSwitch').bootstrapToggle('off') &
		$('#satSwitch').bootstrapToggle('off')
	}
});
