### ISSUE TITLE
Disable mouse pointer on layers with no retrieve info

### ISSUE THREAD

**Issue by rgdonohue** [Danidue1/Halfmoon_Interactive#6]
For layers such as Wetlands, when the user mouses over a polygon, the cursor changes to the pointer hand, indicating that there is some kind of user interaction they're supposed to engage. Either have this interaction do something (like a tooltip/popup) or remove the cursor from those layers.

**Comment by Danidue1** [comment]
This issue has been resolved and will be applied on tonight's (6/22) upload
